# Python CircleCI 2.0 configuration file
name: "Calculator Library"

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
      - uses: actions/checkout@v4
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#        working_directory: ~/repo
